---
  - name: create wordpress VPC
    ec2_vpc:
      state: present
      resource_tags: { "Name": "vpcWordPress" }
      cidr_block: 10.0.0.0/16
      region: eu-west-1
      subnets:
        - cidr: 10.0.1.0/24
          az: eu-west-1a
          resource_tags: { "Name":"snWordPressELBa" }
        - cidr: 10.0.2.0/24
          az: eu-west-1b
          resource_tags: { "Name":"snWordPressELBb" }
        - cidr: 10.0.3.0/24
          az: eu-west-1a
          resource_tags: { "Name":"snWordPressAPPa" }
        - cidr: 10.0.4.0/24
          az: eu-west-1b
          resource_tags: { "Name":"snWordPressAPPb" }
        - cidr: 10.0.5.0/24
          az: eu-west-1a
          resource_tags: { "Name":"snWordPressDBa" }
        - cidr: 10.0.6.0/24
          az: eu-west-1b
          resource_tags: { "Name":"snWordPressDBb" }
      internet_gateway: True
      route_tables:
        - subnets:
          - "10.0.1.0/24"
          - "10.0.2.0/24"
          routes:
            - dest: 0.0.0.0/0
              gw: igw
